#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
h=0
while [ "$h" -le 12 ]
do
	echo "Hour: $h"
	(( h++ ))
	m=1
	while [ "$m" -le 59 ]
	do
	echo "$m"
	let m+=1
	(( m++ ))
	done
	let m=1
	let h+=1
done
