#!/usr/bin/env bash
# This script indefinitely writes I am alive! to the file /tmp/my_process
case $1 in
	start)
		./manage_my_process &
		echo $! > /var/run/my_process.pid &
		echo "manage_my_process started"
		;;
	stop)
		kill "$(cat "/var/run/manage_my_process.pid")" &
		rm /var/run/my_process.pid &
		echo "manage_my_process stopped"
		;;
	restart)
		echo "manage_my_process restarted" > &&
		kill "$(cat "/var/run/my_process.pid")" &&
		rm /var/run/my_process.pid &&
		./manage_my_process &&
		echo $! > /var/run/my_process.pid
		;;
	*) echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
