#!/usr/bin/env bash
# This script indefinitely writes I am alive! to the file /tmp/my_process
PIDFILE=/var/run/my_process.pid

if [ "$PIDFILE" == "start" ]; then
	./manage_my_process &
	echo "$!" > "$PIDFILE"
	echo "manage_my_process started"
elif [ "$PIDFILE" == "stop" ]; then
	pkill -f ./manage_my_process
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$PIDFILE" == "restart" ]; then
	pkill -f ./manage_my_process
	sudo rm /var/run/my_process.pid
	./manage_my_process &
	echo "$!" > "$PIDFILE"
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
